-- Server-only 2DB tables. No browser/Data API access is granted.
CREATE SCHEMA IF NOT EXISTS two_db;
REVOKE ALL ON SCHEMA two_db FROM PUBLIC, anon, authenticated;
SET LOCAL search_path TO two_db;

CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('buyer','seller')), shop TEXT);
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY, seller_id TEXT NOT NULL REFERENCES accounts(id), title TEXT NOT NULL, description TEXT NOT NULL, category TEXT NOT NULL, price_cents INTEGER NOT NULL CHECK(price_cents>0), photo_url TEXT, eligible INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS discounts(code TEXT PRIMARY KEY, percent INTEGER NOT NULL, active INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY, buyer_id TEXT NOT NULL REFERENCES accounts(id), status TEXT NOT NULL, subtotal_cents INTEGER NOT NULL, discount_cents INTEGER NOT NULL, total_cents INTEGER NOT NULL, discount_code TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), product_id TEXT NOT NULL REFERENCES products(id), title TEXT NOT NULL, quantity INTEGER NOT NULL, unit_cents INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS payments(id TEXT PRIMARY KEY, order_id TEXT NOT NULL UNIQUE REFERENCES orders(id), amount_cents INTEGER NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS support_tickets(id TEXT PRIMARY KEY, account_id TEXT NOT NULL REFERENCES accounts(id), subject TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS checkout_requests(buyer_id TEXT NOT NULL REFERENCES accounts(id), request_key TEXT NOT NULL, order_id TEXT NOT NULL REFERENCES orders(id), PRIMARY KEY(buyer_id,request_key));

CREATE INDEX IF NOT EXISTS products_seller_idx ON products(seller_id);
CREATE INDEX IF NOT EXISTS orders_buyer_created_idx ON orders(buyer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS order_items_order_idx ON order_items(order_id);
CREATE INDEX IF NOT EXISTS order_items_product_idx ON order_items(product_id);
CREATE INDEX IF NOT EXISTS support_tickets_account_created_idx ON support_tickets(account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS support_tickets_created_idx ON support_tickets(created_at DESC);
CREATE INDEX IF NOT EXISTS checkout_requests_order_idx ON checkout_requests(order_id);

ALTER TABLE two_db.accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE two_db.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE two_db.discounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE two_db.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE two_db.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE two_db.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE two_db.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE two_db.checkout_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA two_db FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA two_db FROM PUBLIC, anon, authenticated;
